### ISSUE TITLE
error for exampleAlignmentTree.glue 

### ISSUE THREAD

**Issue by lynhsiong** [giffordlabcvr/gluetools#10]
After native  installation (http://glue-tools.cvr.gla.ac.uk/#/installation), when I built the example project, it gave an error:

Exception at line 241 of glue/exampleAlignmentTree.glue
Invoked from line 53 of exampleProject.glue
Error: Linking / constraining reference must not be one of the selected source members.

I have checked the versions of mysql and java, as well as installation of blast+/ mafft/ raxml, and found they all worked well.

Thank you!

**Comment by joshsinger** [comment]
Hi, 

This is fixed in v. 1.1.84, released today. Some error handling code was a bit to strict. Sorry for the delay, i was on vacation.

Unfortunately I've not been able to update the Dockerized version of GLUE, only the jar available on the web. Let me know by email if this is a problem: josh.singer@glasgow.ac.uk
